#baseURL = "http://www.thebetterplay.com"
baseURL = "/"
languageCode = "en-us"
title = "The Better Play"
theme = "custom"

# MENU
[[menu.footer]]
  name = "about"
  identifier = "about"
  url = "/about-us"
[[Languages.de.menu.footer]]
  name = "Ueber uns"
  identifier = "about"
  url = "/de/ueber-uns"

[[menu.footer]]
  name = "luliz"
  identifier = "luliz"
  url = "/luliz/"
[[Languages.de.menu.footer]]
  name = "luliz de"
  identifier = "luliz"
  url = "/de/luliz"

# LANGUAGES
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "The Better Play"
subtitle = "Inspiration for good toys"
weight = 1

[Languages.de]
title = "The Better Play"
subtitle = "Inspiration für gutes Spielzeug"
weight = 2
