#baseURL = "http://www.thebetterplay.com"
baseURL = "/"
languageCode = "en-us"
title = "The Better Play"
theme = "custom"

# FOOTER
# Footer about
[[menu.footer]]
  name = "About"
  identifier = "about"
  url = "/company/about-us"
[[Languages.de.menu.footer]]
  name = "Ueber uns"
  identifier = "about"
  url = "/de/company/ueber-uns"
# Footer affiliate
[[menu.footer]]
  name = "Affiliate Disclaimer"
  identifier = "affiliate-disclaimer"
  url = "/company/affiliate-disclaimer"
[[Languages.de.menu.footer]]
  name = "Amazon Partnerprogramm"
  identifier = "affiliate-disclaimer"
  url = "/de/company/amazon-partnerprogramm"
# Footer imprint
[[menu.footer]]
  name = "Imprint"
  identifier = "imprint"
  url = "/company/imprint"
[[Languages.de.menu.footer]]
  name = "Impressum"
  identifier = "imprint"
  url = "/de/company/impressum"
  # Footer privacy-policy
  [[menu.footer]]
    name = "Privacy Policy"
    identifier = "privacy-policy"
    url = "/company/privacy-policy"
  [[Languages.de.menu.footer]]
    name = "Datenschutzerklärung"
    identifier = "privacy-policy"
    url = "/de/company/datenschutzerklärung"

# LANGUAGES
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "The Better Play"
weight = 1

[Languages.de]
title = "The Better Play"
weight = 2
