#baseURL = "http://www.thebetterplay.com"
baseURL = "/"
languageCode = "en-us"
title = "The Better Play"
theme = "ananke"

# LANGUAGES
DefaultContentLanguage = "en"

[Languages]
[Languages.en]
title = "The Better Play"
subtitle = "Inspiration for good toys"
weight = 1

[Languages.de]
title = "The Better Play"
subtitle = "Inspiration für gutes Spielzeug"
weight = 2

Pages = ['about', 'luliz']

[[menu.main]]
    name = "about hugo"
    pre = "<i class='fa fa-heart'></i>"
    weight = -110
    identifier = "about"
    url = "/about-us"
[[menu.main]]
    name = "getting started"
    pre = "<i class='fa fa-road'></i>"
    weight = -100
    url = "/luliz/"
